catchthepattern:
  app:
    url: 'https://www.catchthepattern.com'
    jwtSecret: '9063551230'
    jwtExpirationMs: 31536000000
    email: noreply@catchthepattern.com
    server: 'https://api.catchthepattern.com'
spring:
  mail:
    username: catchthepattern@gmail.com
    host: smtp.gmail.com
    properties:
      mail:
        smtp:
          starttls:
            required: true
            enable: true
          writetimeout: 10000
          timeout: 10000
          auth: 'true'
          connectiontimeout: 10000
    protocol: smtp
    port: 587
    password: wsmgjmgwgrykopbz
  jpa:
    hibernate:
      ddl-auto: update
  mvc:
    media-types:
      csv: text/csv
alphavantage:
  api: 
server:
  port: 5000
  
paypal:
  sandbox:
    clientId: 
    clientSecret: 
  


# ===============================
# Database
# ===============================

spring.datasource.url: jdbc:mysql://localhost:3306/ctp?allowPublicKeyRetrieval=true&useSSL=false
#spring.datasource.url: jdbc:mysql://192.168.0.12:3306/ctp?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.password: U8adewio

# change to prod:

#spring.datasource.url: jdbc:mysql://catchthepattern.cvcizdxf3wsa.us-east-2.rds.amazonaws.com:3306/ctp?allowPublicKeyRetrieval=true&useSSL=false
#spring.datasource.password: 



spring.datasource.driver-class-name: com.mysql.cj.jdbc.Driver
spring.datasource.username: root
spring.jpa.hibernate.ddl-auto: update



#spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
#spring.jpa.database-platform: org.hibernate.dialect.MySQL55Dialect
#spring.datasource.url=jdbc:mysql://localhost:3306/tugc_db?useSSL=false
# database init, supports mysql too
#spring.jpa.show-sql: true
#spring.cloud.gcp.sql.database-name: ctp
#spring.cloud.gcp.sql.instance-connection-name: catchthepattern:us-central1:ctp

# So app starts despite "table already exists" errors.
#spring.datasource.continue-on-error: true
# Enforces database initialization
#spring.datasource.initialization-mode: always
  
#spring.jpa.hibernate.ddl-auto=update
#spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/ctp
#spring.datasource.username=yingjie
#spring.datasource.password=
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#server.port = 8080
#spring.mail.protocol=smtp
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username=catchthepattern@gmail.com
#spring.mail.password=
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true
#spring.mail.properties.mail.smtp.starttls.required=true
#spring.mail.properties.mail.smtp.connectiontimeout=10000
#spring.mail.properties.mail.smtp.timeout=10000
#spring.mail.properties.mail.smtp.writetimeout=10000
#catchthepattern.app.jwtSecret=9063551230
#catchthepattern.app.jwtExpirationMs=86400000
#catchthepattern.app.url=http://localhost:4210
#catchthepattern.app.server=http://localhost:8080
#catchthepattern.app.email=noreply@catchthepattern.com
#alphavantage.api=ZYWW4DXQ8K38TMU8
#spring.mvc.media-types.csv=text/csv


# Loco yaml export: Simple YAML object
# Project: 1.properties conversion
# Release: Working copy
# Locale: en, English
# Exported by: Unregistered user
# Exported at: Tue, 18 Sep 2018 23:23:36 -0500

# ===============================
# Database
# ===============================

#spring.cloud.appId=tugc-906355
#spring.cloud.gcp.project-id=tugc-906355
#spring.cloud.gcp.sql.instance-connection-name=tugc-906355:us-central1:tugc-906355-db
#spring.cloud.gcp.sql.database-name=tugc_db
#spring.datasource.username=root
#spring.datasource.password=
#spring.datasource.continue-on-error=true
#spring.datasource.initialization-mode=always
#spring.cloud.gcp.credentials.location=file:./src/main/resources/keys-gcp.json
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL5InnoDBDialect
#spring.jpa.database-platform=org.hibernate.dialect.MySQL55Dialect
#spring.jpa.hibernate.ddl-auto=update

#spring.datasource.url=jdbc:mysql://localhost:3306/tugc_db?useSSL=false
#spring.datasource.url=jdbc:mysql://35.239.220.134:3306/tugc_db?useSSL=false
#spring.datasource.username=root
#spring.datasource.password=

# database init, supports mysql too



#spring.jpa.show-sql: true
 

# ===============================
# Session
# ===============================

#spring.session.store-type=redis # Session store type.
#spring.redis.host=localhost # Redis server host.
#spring.redis.password= # Login password of the redis server.
#spring.redis.port=6379 # Redis server port.

# ===============================
# JSP
# ===============================
#spring.mvc.view.prefix=/WEB-INF/jsp/
#spring.mvc.view.suffix=.jsp

# ===============================
# TOMCAT
# ===============================

#server.address=127.0.0.1
#server.error.whitelabel.enabled=false
#server.tomcat.accesslog.enabled=true

# ===============================
# SMTP EMAIL
# ===============================


#spring.mail.host = smtp.gmail.com
#spring.mail.username=contact@tugc.org
#spring.mail.password=
#spring.mail.port = 465
#spring.mail.port = 587
#spring.mail.properties.mail.smtp.auth = true
#spring.mail.properties.mail.smtp.starttls.enable = true

# ===============================
#  LOGGING
# ===============================
#logging.level.org.springframework.web=DEBUGf
#logging.level.org.hibernate=ERROR


# ===============================
#  Security 
# ===============================



#free
#alphavantage.api=37SNAFOHXTCOO2E3

#premium 75/minute


